"""fase2_ventas_catalogo_campos_faltantes

Revision ID: 1deaa124b5c3
Revises: 7f09d19e6e48
Create Date: 2026-07-09 15:54:54.185646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1deaa124b5c3'
down_revision: Union[str, Sequence[str], None] = '7f09d19e6e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comprobante', sa.Column('documentoCliente', sa.String(length=15), nullable=True))
    op.add_column('Comprobante', sa.Column('nombreCliente', sa.String(length=200), nullable=True))
    op.add_column('Comprobante', sa.Column('serie', sa.String(length=4), nullable=True))
    op.add_column('Comprobante', sa.Column('correlativo', sa.Integer(), nullable=True))
    op.add_column('Comprobante', sa.Column('estadoSunat', sa.String(length=20), nullable=True))
    op.add_column('Pedido', sa.Column('distrito', sa.String(length=100), nullable=True))
    op.add_column('Producto', sa.Column('stockMinimo', sa.Integer(), nullable=True))
    op.add_column('Producto', sa.Column('imagenUrl', sa.String(length=500), nullable=True))
    op.add_column('Producto', sa.Column('presentacion', sa.String(length=100), nullable=True))
    op.add_column('RecetaMedica', sa.Column('codigoProducto', sa.Integer(), nullable=True))
    op.add_column('RecetaMedica', sa.Column('cmpMedico', sa.String(length=50), nullable=True))
    op.add_column('RecetaMedica', sa.Column('imagenUrl', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'RecetaMedica', 'Producto', ['codigoProducto'], ['codigoProducto'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RecetaMedica', type_='foreignkey')
    op.drop_column('RecetaMedica', 'imagenUrl')
    op.drop_column('RecetaMedica', 'cmpMedico')
    op.drop_column('RecetaMedica', 'codigoProducto')
    op.drop_column('Producto', 'presentacion')
    op.drop_column('Producto', 'imagenUrl')
    op.drop_column('Producto', 'stockMinimo')
    op.drop_column('Pedido', 'distrito')
    op.drop_column('Comprobante', 'estadoSunat')
    op.drop_column('Comprobante', 'correlativo')
    op.drop_column('Comprobante', 'serie')
    op.drop_column('Comprobante', 'nombreCliente')
    op.drop_column('Comprobante', 'documentoCliente')
    # ### end Alembic commands ###
