"""receta_medica_codigo_cliente

Revision ID: 35efbe72847e
Revises: 44b41fc4a9cb
Create Date: 2026-07-09 17:54:38.711771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35efbe72847e'
down_revision: Union[str, Sequence[str], None] = '44b41fc4a9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RecetaMedica', sa.Column('codigoCliente', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'RecetaMedica', 'Cliente', ['codigoCliente'], ['codigoCliente'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RecetaMedica', type_='foreignkey')
    op.drop_column('RecetaMedica', 'codigoCliente')
    # ### end Alembic commands ###
