"""detalle_pedido_nombre_producto

Revision ID: 44b41fc4a9cb
Revises: 1deaa124b5c3
Create Date: 2026-07-09 16:09:17.950767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b41fc4a9cb'
down_revision: Union[str, Sequence[str], None] = '1deaa124b5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DetallePedido', sa.Column('nombreProducto', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DetallePedido', 'nombreProducto')
    # ### end Alembic commands ###
