"""baseline

Revision ID: 5d73e7c02129
Revises: 
Create Date: 2026-07-09 01:32:57.563133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d73e7c02129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('codigoCategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigoCategoria')
    )
    op.create_table('Cliente',
    sa.Column('codigoCliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('dni', sa.String(length=15), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correoElectronico', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codigoCliente'),
    sa.UniqueConstraint('correoElectronico'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('Laboratorio',
    sa.Column('codigoLaboratorio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('codigoLaboratorio')
    )
    op.create_table('Proveedor',
    sa.Column('rucProveedor', sa.String(length=11), nullable=False),
    sa.Column('razonSocial', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correoElectronico', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('rucProveedor')
    )
    op.create_table('Repartidor',
    sa.Column('codigoRepartidor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codigoRepartidor')
    )
    op.create_table('CarritodeCompras',
    sa.Column('codigoCarrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoCliente', sa.Integer(), nullable=True),
    sa.Column('fechaCreacion', sa.Date(), nullable=True),
    sa.Column('totalProductos', sa.Integer(), nullable=True),
    sa.Column('montoEstimado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['codigoCliente'], ['Cliente.codigoCliente'], ),
    sa.PrimaryKeyConstraint('codigoCarrito')
    )
    op.create_table('OrdenDeCompra',
    sa.Column('numeroOrden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rucProveedor', sa.String(length=11), nullable=True),
    sa.Column('fechaEmision', sa.Date(), nullable=True),
    sa.Column('montoTotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['rucProveedor'], ['Proveedor.rucProveedor'], ),
    sa.PrimaryKeyConstraint('numeroOrden')
    )
    op.create_table('Pedido',
    sa.Column('numeroPedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoCliente', sa.Integer(), nullable=True),
    sa.Column('fechaPedido', sa.Date(), nullable=True),
    sa.Column('estadoPedido', sa.String(length=50), nullable=True),
    sa.Column('montoTotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('direccionEntrega', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['codigoCliente'], ['Cliente.codigoCliente'], ),
    sa.PrimaryKeyConstraint('numeroPedido')
    )
    op.create_table('Producto',
    sa.Column('codigoProducto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoCategoria', sa.Integer(), nullable=True),
    sa.Column('codigoLaboratorio', sa.Integer(), nullable=True),
    sa.Column('nombreProducto', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precioVenta', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('condicionVenta', sa.String(length=50), nullable=True),
    sa.Column('stockDisponible', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codigoCategoria'], ['Categoria.codigoCategoria'], ),
    sa.ForeignKeyConstraint(['codigoLaboratorio'], ['Laboratorio.codigoLaboratorio'], ),
    sa.PrimaryKeyConstraint('codigoProducto')
    )
    op.create_table('DetalleOrdenCompra',
    sa.Column('idDetalleOrden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numeroOrden', sa.Integer(), nullable=True),
    sa.Column('codigoProducto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precioUnitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['codigoProducto'], ['Producto.codigoProducto'], ),
    sa.ForeignKeyConstraint(['numeroOrden'], ['OrdenDeCompra.numeroOrden'], ),
    sa.PrimaryKeyConstraint('idDetalleOrden')
    )
    op.create_table('DetallePedido',
    sa.Column('idDetallePedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numeroPedido', sa.Integer(), nullable=True),
    sa.Column('codigoProducto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precioUnitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['codigoProducto'], ['Producto.codigoProducto'], ),
    sa.ForeignKeyConstraint(['numeroPedido'], ['Pedido.numeroPedido'], ),
    sa.PrimaryKeyConstraint('idDetallePedido')
    )
    op.create_table('Entrega',
    sa.Column('codigoEntrega', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numeroPedido', sa.Integer(), nullable=True),
    sa.Column('codigoRepartidor', sa.Integer(), nullable=True),
    sa.Column('fechaEntrega', sa.Date(), nullable=True),
    sa.Column('direccionEntrega', sa.String(length=255), nullable=True),
    sa.Column('estadoEntrega', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['codigoRepartidor'], ['Repartidor.codigoRepartidor'], ),
    sa.ForeignKeyConstraint(['numeroPedido'], ['Pedido.numeroPedido'], ),
    sa.PrimaryKeyConstraint('codigoEntrega')
    )
    op.create_table('Lote',
    sa.Column('codigoLote', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoProducto', sa.Integer(), nullable=True),
    sa.Column('numeroLote', sa.String(length=100), nullable=False),
    sa.Column('fechaVencimiento', sa.Date(), nullable=True),
    sa.Column('stockDisponible', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['codigoProducto'], ['Producto.codigoProducto'], ),
    sa.PrimaryKeyConstraint('codigoLote'),
    sa.UniqueConstraint('numeroLote')
    )
    op.create_table('Pago',
    sa.Column('codigoPago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numeroPedido', sa.Integer(), nullable=True),
    sa.Column('fechaPago', sa.Date(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('metodoPago', sa.String(length=50), nullable=True),
    sa.Column('estadoPago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['numeroPedido'], ['Pedido.numeroPedido'], ),
    sa.PrimaryKeyConstraint('codigoPago')
    )
    op.create_table('RecetaMedica',
    sa.Column('numeroReceta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numeroPedido', sa.Integer(), nullable=True),
    sa.Column('nombrePaciente', sa.String(length=150), nullable=True),
    sa.Column('medicoTratante', sa.String(length=150), nullable=True),
    sa.Column('fechaEmision', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['numeroPedido'], ['Pedido.numeroPedido'], ),
    sa.PrimaryKeyConstraint('numeroReceta')
    )
    op.create_table('Comprobante',
    sa.Column('numeroComprobante', sa.String(length=20), nullable=False),
    sa.Column('codigoPago', sa.Integer(), nullable=True),
    sa.Column('tipoComprobante', sa.String(length=50), nullable=True),
    sa.Column('fechaEmision', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('igv', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['codigoPago'], ['Pago.codigoPago'], ),
    sa.PrimaryKeyConstraint('numeroComprobante')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comprobante')
    op.drop_table('RecetaMedica')
    op.drop_table('Pago')
    op.drop_table('Lote')
    op.drop_table('Entrega')
    op.drop_table('DetallePedido')
    op.drop_table('DetalleOrdenCompra')
    op.drop_table('Producto')
    op.drop_table('Pedido')
    op.drop_table('OrdenDeCompra')
    op.drop_table('CarritodeCompras')
    op.drop_table('Repartidor')
    op.drop_table('Proveedor')
    op.drop_table('Laboratorio')
    op.drop_table('Cliente')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
