"""seguridad_usuario_registro_auditoria

Revision ID: 7f09d19e6e48
Revises: 5d73e7c02129
Create Date: 2026-07-09 02:20:02.428540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f09d19e6e48'
down_revision: Union[str, Sequence[str], None] = '5d73e7c02129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('codigoUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('correoElectronico', sa.String(length=150), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('codigoCliente', sa.Integer(), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimoAcceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigoCliente'], ['Cliente.codigoCliente'], ),
    sa.PrimaryKeyConstraint('codigoUsuario'),
    sa.UniqueConstraint('correoElectronico')
    )
    op.create_table('RegistroAuditoria',
    sa.Column('codigoRegistro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoUsuario', sa.Integer(), nullable=True),
    sa.Column('correoUsuario', sa.String(length=150), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=True),
    sa.Column('entidadId', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fechaHora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['codigoUsuario'], ['Usuario.codigoUsuario'], ),
    sa.PrimaryKeyConstraint('codigoRegistro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RegistroAuditoria')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
